<?php

namespace AppBundle\Repository;

/**
 * AlquilerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlquilerRepository extends \Doctrine\ORM\EntityRepository{

	public function obtener_puntos_cliente($id_cliente){
		$puntos_fidelizacion =  $this->getEntityManager()
            ->createQuery(
                'SELECT 
                    sum(tp.puntuacion)
                FROM   AppBundle:Alquiler a 
                inner join a.tipo_pelicula tp
                where 
                    a.cliente in (:id_cliente)
                '

            )
            ->setParameter('id_cliente', $id_cliente)
            ->getSingleScalarResult();

        return $puntos_fidelizacion != null ? $puntos_fidelizacion : 0; 
	}

}
