<?php

namespace AppBundle\Repository;

/**
 * PeliculaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeliculaRepository extends \Doctrine\ORM\EntityRepository{


	public function buscar_tipo_pelicula($id_tipo_pelicula){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT 
                	p
                FROM   AppBundle:Pelicula p 
                where 
                    p.tipo_pelicula = :id_tipo_pelicula
                '

            )
            ->setParameter('id_tipo_pelicula', $id_tipo_pelicula)
            ->getResult();
    }


    public function obtener_peliculas_lista($list_peliculas){

        $lista_peliculas_string = join(",", $list_peliculas);

        return $this->getEntityManager()
            ->createQuery(
                "SELECT 
                    p, tp
                FROM   AppBundle:Pelicula p 
                inner join p.tipo_pelicula tp
                where 
                    p.id in ($lista_peliculas_string)
                "

            )
            ->getResult();
    }
}
