<?php

namespace AppBundle\Repository;

/**
 * TipoPeliculaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPeliculaRepository extends \Doctrine\ORM\EntityRepository
{
}
